# Site settings
title:       Boyi Li
email:       It's My Fucking Email!^_^
author:      John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://boylee1111.github.io"

# Google analytics
google_analytics: true

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: boylee1111
google_plus_id:
linkedin_username: boylee
facebook_username: boylee1111
twitter_username: boylee1111
instagram_username: boylee1111
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
kramdown:
  input: GFM
markdown:     kramdown
permalink:    pretty
paginate:     10
sass:
  compressed: true

highlighter: pygments