# Site settings
title:       Boyi Li
email:       It's my Email!^_^
author:      John Otander
description: "Blog of Boylee(Boyi Li), a software engineering. Here are some development articles and everything about me."
baseurl:     ""
url:         "http://boylee.me"

# Google analytics
google_analytics: true

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: boylee1111
google_plus_id:
linkedin_username: boylee
weibo_id: boylee1111
facebook_username: boylee1111
twitter_username: boylee1111
instagram_username: boylee1111
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
kramdown:
  input: GFM
markdown:     kramdown
permalink:    pretty
paginate:     10
paginate_path: "blog/page:num/"
sass:
  compressed: true

highlighter: pygments